services:
  life-4-cut-mysql-development:
    platform: linux/amd64
    container_name: life-4-cut-mysql-development
    image: 'mysql:8.0.27'
    ports:
      - '3325:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'life-4-cut-development'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci