spring:
  profiles:
    default: 'local'
    group:
      local: 'common,local'
      dev: 'common'
      prod: 'common'

---
spring:
  config:
    activate:
      on-profile: 'common'
  jpa:
    database-platform: 'org.hibernate.dialect.MySQLDialect'
    database: MYSQL
    hibernate:
      ddl-auto: none

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao-login:
            client-id: 7e558adbc7b32496ba547bfbbaa19261
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao-login:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  config:
    activate:
      on-profile: 'local'
  datasource:
    url: "jdbc:mysql://localhost:3325/life-4-cut-development"
    username: "test"
    password: "test"
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
      read-only: false
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    org.springframework.security: TRACE
